// <auto-generated />
using System;
using Alkonof_Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alkonof_Backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260810230247_SeedAdminData")]
    partial class SeedAdminData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Audits.AuditChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditChange");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Audits.AuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<Guid>("AuditChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuditChangeId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditEntity");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerAnswer")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponsibleAnswer")
                        .HasColumnType("int");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique()
                        .HasFilter("[ContractId] IS NOT NULL");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ResponsibleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.OrderBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderBooking");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Complains.Complain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ResolutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ResolutionId");

                    b.ToTable("Complain");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Complains.Resolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComplintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resolution");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasFilter("[ProjectId] IS NOT NULL");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5"),
                            PermissionType = 0
                        },
                        new
                        {
                            Id = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b"),
                            PermissionType = 1
                        },
                        new
                        {
                            Id = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a"),
                            PermissionType = 2
                        },
                        new
                        {
                            Id = new Guid("f4d3e2c1-b0a9-4b8c-9a7b-6f5e4d3c2b1a"),
                            PermissionType = 3
                        },
                        new
                        {
                            Id = new Guid("a9b8c7d6-e5f4-4b3c-8a7b-6f5e4d3c2b1a"),
                            PermissionType = 4
                        });
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.PermissionGrop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperationPermission")
                        .HasColumnType("int");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.ToTable("PermissionGrop");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93880cce-62a7-4fc3-b661-df8d2bef8e08"),
                            OperationPermission = 0,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("fd2da7fd-ceac-4285-9f72-3f9c807f9363"),
                            OperationPermission = 1,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("b2e56dc2-ebcd-4b72-8b60-cf6b18f6f25c"),
                            OperationPermission = 2,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("fa8d3781-b92a-4e81-904e-90db754eb6ba"),
                            OperationPermission = 3,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("c5c0fb57-e57d-480e-aba3-d1735d724bf0"),
                            OperationPermission = 4,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("9194218c-9520-4645-b54a-bd580a261024"),
                            OperationPermission = 6,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("8cd2e626-b4c3-4199-85b1-4c449c9270a2"),
                            OperationPermission = 5,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("45486488-cbfb-445b-910a-b7a33ab9e082"),
                            OperationPermission = 7,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("035215cd-def9-4eb1-8154-b90440e03ed0"),
                            OperationPermission = 11,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("70110e97-aa5c-439b-8472-d0f0cfe1292a"),
                            OperationPermission = 0,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("47ea4e1a-7f7d-4db2-a43d-d4236d83efea"),
                            OperationPermission = 1,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("3bce99f3-e328-4f75-bb78-9aeaa763fdc7"),
                            OperationPermission = 2,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("9cf6bbae-f4b5-4463-a71b-f6092d7bd08d"),
                            OperationPermission = 3,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("0b256676-95f2-4502-9ec0-7575e0596096"),
                            OperationPermission = 7,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("e3e358e2-2046-450c-b624-afaf5c73f593"),
                            OperationPermission = 8,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("78f4ffc1-9e2b-4823-ba27-4322cd874237"),
                            OperationPermission = 9,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("58dd6e2b-1c3d-42f0-b0e4-7442c4f290cc"),
                            OperationPermission = 10,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("64a3390b-9b6f-416c-946b-7c52feee6fa1"),
                            OperationPermission = 0,
                            PermissionId = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("8b4068a0-5514-4e85-9fcf-fca958c852a9"),
                            OperationPermission = 1,
                            PermissionId = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("07da9005-8c5a-42a0-a77a-76ef8c54b8dd"),
                            OperationPermission = 2,
                            PermissionId = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("e5827b2b-b78c-4c53-9c92-fcde058aeb62"),
                            OperationPermission = 3,
                            PermissionId = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("3769dbf1-ffff-4254-833a-21a5e9aaa9a1"),
                            OperationPermission = 10,
                            PermissionId = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a")
                        });
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("caf312c6-681b-44b4-9637-1c7e60ef7032"),
                            Email = "awad@gmail.com",
                            IsDeleted = false,
                            Name = "Awad",
                            Number = "0986174521",
                            Password = "E9230CF95C159AD83A0E7AFAF1A23B0496A5C59FB2D2ACF7D9077A5C0EEE2713",
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5"),
                            Role = 0
                        });
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Meetings.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeetingNumber")
                        .HasColumnType("int");

                    b.Property<int>("OutCome")
                        .HasColumnType("int");

                    b.Property<int>("ResponsibleStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Meetings.PrepareMeeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("MeetingId")
                        .IsUnique();

                    b.ToTable("PrepareMeeting");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TempletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TempletId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Notifications.NotificationTemplet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reference")
                        .HasColumnType("int");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationTemplet");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.ProjectReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectReport");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.ProjectStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponsibalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResponsibalId");

                    b.ToTable("ProjectStaff");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ActualEndedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.StageImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("StageImage");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.TaskTabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ActualEndedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("TaskTabel");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Schedualing.TimeTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("TimeTable");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<Guid>("ListId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ListId1");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.TodoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Expired")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserSecurityHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Audits.AuditEntity", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Audits.AuditChange", "AuditChange")
                        .WithMany("AuditEntities")
                        .HasForeignKey("AuditChangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "User")
                        .WithMany("AuditEntities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditChange");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.Booking", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Contracts.Contract", "Contract")
                        .WithOne("Booking")
                        .HasForeignKey("Alkonof_Backend.Domain.Entities.Bookings.Booking", "ContractId");

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", null)
                        .WithMany("CustomerBookings")
                        .HasForeignKey("UserId");

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", null)
                        .WithMany("ResponsibalBookings")
                        .HasForeignKey("UserId1");

                    b.Navigation("Contract");

                    b.Navigation("Customer");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.OrderBooking", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Customer")
                        .WithMany("OrderBookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Bookings.Service", "Service")
                        .WithMany("OrderBookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Complains.Complain", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Customer")
                        .WithMany("Complains")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Complains.Resolution", null)
                        .WithMany("Complains")
                        .HasForeignKey("ResolutionId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Contracts.Contract", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", "Project")
                        .WithOne("Contract")
                        .HasForeignKey("Alkonof_Backend.Domain.Entities.Contracts.Contract", "ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.PermissionGrop", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.Permission", "Permission")
                        .WithMany("PermissionGrops")
                        .HasForeignKey("PermissionId");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.User", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.Permission", "Permission")
                        .WithMany("Users")
                        .HasForeignKey("PermissionId");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Meetings.PrepareMeeting", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Bookings.Booking", "Booking")
                        .WithMany("PrepareMeetings")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Meetings.Meeting", "Meeting")
                        .WithOne("PrepareMeeting")
                        .HasForeignKey("Alkonof_Backend.Domain.Entities.Meetings.PrepareMeeting", "MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Notifications.Notification", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Notifications.NotificationTemplet", "Templet")
                        .WithMany("Notifications")
                        .HasForeignKey("TempletId");

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Templet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.ProjectReport", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", "Project")
                        .WithMany("ProjectReport")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.ProjectStaff", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", "Project")
                        .WithMany("ProjectStaffs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Responsibal")
                        .WithMany("ProjectStaffs")
                        .HasForeignKey("ResponsibalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Responsibal");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Stage", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", "Project")
                        .WithMany("Stages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.StageImage", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Stage", "Stage")
                        .WithMany("StageImages")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.TaskTabel", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Stage", "Stage")
                        .WithMany("Tasks")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Schedualing.TimeTable", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.TodoItem", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.TodoList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.TodoList", b =>
                {
                    b.OwnsOne("Alkonof_Backend.Domain.ValueObjects.Colour", "Colour", b1 =>
                        {
                            b1.Property<Guid>("TodoListId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TodoListId");

                            b1.ToTable("TodoLists");

                            b1.WithOwner()
                                .HasForeignKey("TodoListId");
                        });

                    b.Navigation("Colour")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Audits.AuditChange", b =>
                {
                    b.Navigation("AuditEntities");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.Booking", b =>
                {
                    b.Navigation("PrepareMeetings");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.Service", b =>
                {
                    b.Navigation("OrderBookings");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Complains.Resolution", b =>
                {
                    b.Navigation("Complains");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Contracts.Contract", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.Permission", b =>
                {
                    b.Navigation("PermissionGrops");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("AuditEntities");

                    b.Navigation("Complains");

                    b.Navigation("CustomerBookings");

                    b.Navigation("Notifications");

                    b.Navigation("OrderBookings");

                    b.Navigation("ProjectStaffs");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ResponsibalBookings");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Meetings.Meeting", b =>
                {
                    b.Navigation("PrepareMeeting");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Notifications.NotificationTemplet", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("ProjectReport");

                    b.Navigation("ProjectStaffs");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Stage", b =>
                {
                    b.Navigation("StageImages");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.TodoList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
