// <auto-generated />
using System;
using Alkonof_Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alkonof_Backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Audits.AuditChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditChange");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Audits.AuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<Guid>("AuditChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuditChangeId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditEntity");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerAnswer")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponsibleAnswer")
                        .HasColumnType("int");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique()
                        .HasFilter("[ContractId] IS NOT NULL");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ResponsibleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.OrderBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderBooking");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Complains.Complain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ResolutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ResolutionId");

                    b.ToTable("Complain");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Complains.Resolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComplintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resolution");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasFilter("[ProjectId] IS NOT NULL");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5"),
                            PermissionType = 0
                        },
                        new
                        {
                            Id = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b"),
                            PermissionType = 1
                        },
                        new
                        {
                            Id = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a"),
                            PermissionType = 2
                        },
                        new
                        {
                            Id = new Guid("f4d3e2c1-b0a9-4b8c-9a7b-6f5e4d3c2b1a"),
                            PermissionType = 3
                        },
                        new
                        {
                            Id = new Guid("a9b8c7d6-e5f4-4b3c-8a7b-6f5e4d3c2b1a"),
                            PermissionType = 4
                        });
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.PermissionGrop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperationPermission")
                        .HasColumnType("int");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.ToTable("PermissionGrop");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd5552fa-3934-4abc-a779-eee4b1266d3b"),
                            OperationPermission = 0,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("ba0cb569-e7ed-4274-ab10-e1e6400746cc"),
                            OperationPermission = 1,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("cd4b109b-be5c-41e2-9c29-347ad2a69c1c"),
                            OperationPermission = 2,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("09c96fcb-e0d1-4d3d-ae5f-95ff861f6df7"),
                            OperationPermission = 3,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("5635da7e-424c-414f-b091-085a360a2a07"),
                            OperationPermission = 4,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("5f1cde02-a082-441d-b727-86f64e92b59c"),
                            OperationPermission = 6,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("695d0db5-8530-4df3-9601-7f600dd98eaa"),
                            OperationPermission = 5,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("cb8cf96f-79d2-4f90-b930-d813425cb3f1"),
                            OperationPermission = 7,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("51ce78d1-758d-494c-915f-1019a763ed19"),
                            OperationPermission = 11,
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5")
                        },
                        new
                        {
                            Id = new Guid("7b3192f4-f167-4323-8919-79420c8a697d"),
                            OperationPermission = 0,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("ecda487f-a9ae-4f97-903a-89261afe4ad7"),
                            OperationPermission = 1,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("16dfcd9c-6244-4671-9c1c-ba1285e35e9f"),
                            OperationPermission = 2,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("fdcdd1c3-809d-4b45-81fd-e058fb42ab95"),
                            OperationPermission = 3,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("649e60c0-fcc8-44c0-af8a-0b6d140cbd63"),
                            OperationPermission = 7,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("ca7b64f9-9974-4620-bdbb-f770bfc94f2f"),
                            OperationPermission = 8,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("4c6bea8b-c93d-4527-8fd3-550e73f4f21c"),
                            OperationPermission = 9,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("c170d887-d317-4968-a351-253e1000536b"),
                            OperationPermission = 10,
                            PermissionId = new Guid("8a5c8e6c-4f3b-4b2c-8a7f-8d3e2f5b9a1b")
                        },
                        new
                        {
                            Id = new Guid("5a352120-cf4e-4983-8422-5570ad82b864"),
                            OperationPermission = 0,
                            PermissionId = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("bb215ebd-568b-4fdd-9ddd-2cb3a09ecdd5"),
                            OperationPermission = 1,
                            PermissionId = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("6595cb2b-fb7c-4596-8eb5-096fa0ae9d9c"),
                            OperationPermission = 2,
                            PermissionId = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("44f72a6b-ccfe-4600-b095-53836da1b970"),
                            OperationPermission = 3,
                            PermissionId = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("4fda9fa9-88cf-4f46-be10-a8d5ac7fdd52"),
                            OperationPermission = 10,
                            PermissionId = new Guid("3c1b2a9d-4e8f-4b1a-9c8d-6f5e4d3c2b1a")
                        });
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("Specialization")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3bf312c6-681b-44b4-9637-1c7e60e2e932"),
                            Email = "awad@gmail.com",
                            IsDeleted = false,
                            Name = "Awad",
                            Number = "0986174521",
                            Password = "E9230CF95C159AD83A0E7AFAF1A23B0496A5C59FB2D2ACF7D9077A5C0EEE2713",
                            PermissionId = new Guid("0a794768-ab8a-4a07-b8a0-424b5e5df9d5"),
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("1a7e5c9d-3f21-4b86-9c42-7d15e8a6b903"),
                            Email = "ahmad@gmail.com",
                            IsDeleted = false,
                            Name = "Ahmad",
                            Number = "0986123456",
                            Password = "E9230CF95C159AD83A0E7AFAF1A23B0496A5C59FB2D2ACF7D9077A5C0EEE2713",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("1a7e5c9d-3f21-1596-9c42-7d15e8e36903"),
                            Email = "ahmad2@gmail.com",
                            IsDeleted = false,
                            Name = "Ahmad2",
                            Number = "0986123456",
                            Password = "E9230CF95C159AD83A0E7AFAF1A23B0496A5C59FB2D2ACF7D9077A5C0EEE2713",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("1a7e5c9d-3f21-4b86-7e5c-7d15e8a6b903"),
                            Email = "ahmad3@gmail.com",
                            IsDeleted = false,
                            Name = "Ahmad3",
                            Number = "0986123456",
                            Password = "E9230CF95C159AD83A0E7AFAF1A23B0496A5C59FB2D2ACF7D9077A5C0EEE2713",
                            Role = 2,
                            Specialization = 0
                        },
                        new
                        {
                            Id = new Guid("5b92d714-8e36-4c1a-a057-29f6b83dc9d5"),
                            Email = "mohammad@gmail.com",
                            IsDeleted = false,
                            Name = "Mohammad",
                            Number = "0986234567",
                            Password = "E9230CF95C159AD83A0E7AFAF1A23B0496A5C59FB2D2ACF7D9077A5C0EEE2713",
                            Role = 1,
                            Specialization = 5
                        },
                        new
                        {
                            Id = new Guid("e4386f21-7c95-4a03-bd18-52a9e6073f64"),
                            Email = "omar@gmail.com",
                            IsDeleted = false,
                            Name = "Omar",
                            Number = "0986345678",
                            Password = "E9230CF95C159AD83A0E7AFAF1A23B0496A5C59FB2D2ACF7D9077A5C0EEE2713",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Meetings.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeetingNumber")
                        .HasColumnType("int");

                    b.Property<int>("OutCome")
                        .HasColumnType("int");

                    b.Property<int>("ResponsibleStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Meetings.PrepareMeeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("MeetingId")
                        .IsUnique();

                    b.ToTable("PrepareMeeting");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TempletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TempletId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Notifications.NotificationTemplet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reference")
                        .HasColumnType("int");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationTemplet");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.ProjectReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectReport");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.ProjectStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponsibalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResponsibalId");

                    b.ToTable("ProjectStaff");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ActualEndedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.StageImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("StageImage");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.TaskTabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ActualEndedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("TaskTabel");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Schedualing.TimeTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("TimeTable");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<Guid>("ListId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ListId1");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.TodoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Expired")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserSecurityHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[OutboxId] IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Audits.AuditEntity", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Audits.AuditChange", "AuditChange")
                        .WithMany("AuditEntities")
                        .HasForeignKey("AuditChangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "User")
                        .WithMany("AuditEntities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditChange");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.Booking", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Contracts.Contract", "Contract")
                        .WithOne("Booking")
                        .HasForeignKey("Alkonof_Backend.Domain.Entities.Bookings.Booking", "ContractId");

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", null)
                        .WithMany("CustomerBookings")
                        .HasForeignKey("UserId");

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", null)
                        .WithMany("ResponsibalBookings")
                        .HasForeignKey("UserId1");

                    b.Navigation("Contract");

                    b.Navigation("Customer");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.OrderBooking", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Customer")
                        .WithMany("OrderBookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Bookings.Service", "Service")
                        .WithMany("OrderBookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Complains.Complain", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Customer")
                        .WithMany("Complains")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Complains.Resolution", null)
                        .WithMany("Complains")
                        .HasForeignKey("ResolutionId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Contracts.Contract", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", "Project")
                        .WithOne("Contract")
                        .HasForeignKey("Alkonof_Backend.Domain.Entities.Contracts.Contract", "ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.PermissionGrop", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.Permission", "Permission")
                        .WithMany("PermissionGrops")
                        .HasForeignKey("PermissionId");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.User", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.Permission", "Permission")
                        .WithMany("Users")
                        .HasForeignKey("PermissionId");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Meetings.PrepareMeeting", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Bookings.Booking", "Booking")
                        .WithMany("PrepareMeetings")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Meetings.Meeting", "Meeting")
                        .WithOne("PrepareMeeting")
                        .HasForeignKey("Alkonof_Backend.Domain.Entities.Meetings.PrepareMeeting", "MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Notifications.Notification", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Notifications.NotificationTemplet", "Templet")
                        .WithMany("Notifications")
                        .HasForeignKey("TempletId");

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Templet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.ProjectReport", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", "Project")
                        .WithMany("ProjectReport")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.ProjectStaff", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", "Project")
                        .WithMany("ProjectStaffs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Responsibal")
                        .WithMany("ProjectStaffs")
                        .HasForeignKey("ResponsibalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Responsibal");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Stage", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", "Project")
                        .WithMany("Stages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.StageImage", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Stage", "Stage")
                        .WithMany("StageImages")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.TaskTabel", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Stage", "Stage")
                        .WithMany("Tasks")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Schedualing.TimeTable", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.TodoItem", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.TodoList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.TodoList", b =>
                {
                    b.OwnsOne("Alkonof_Backend.Domain.ValueObjects.Colour", "Colour", b1 =>
                        {
                            b1.Property<Guid>("TodoListId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TodoListId");

                            b1.ToTable("TodoLists");

                            b1.WithOwner()
                                .HasForeignKey("TodoListId");
                        });

                    b.Navigation("Colour")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("Alkonof_Backend.Domain.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Audits.AuditChange", b =>
                {
                    b.Navigation("AuditEntities");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.Booking", b =>
                {
                    b.Navigation("PrepareMeetings");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Bookings.Service", b =>
                {
                    b.Navigation("OrderBookings");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Complains.Resolution", b =>
                {
                    b.Navigation("Complains");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Contracts.Contract", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.Permission", b =>
                {
                    b.Navigation("PermissionGrops");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("AuditEntities");

                    b.Navigation("Complains");

                    b.Navigation("CustomerBookings");

                    b.Navigation("Notifications");

                    b.Navigation("OrderBookings");

                    b.Navigation("ProjectStaffs");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ResponsibalBookings");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Meetings.Meeting", b =>
                {
                    b.Navigation("PrepareMeeting");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.Notifications.NotificationTemplet", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Project", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("ProjectReport");

                    b.Navigation("ProjectStaffs");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.ProjectMonitoring.Stage", b =>
                {
                    b.Navigation("StageImages");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Alkonof_Backend.Domain.Entities.TodoList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
